name: geliyo_app
description: Kargo dağıtım uygulaması

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  firebase_auth: ^4.15.3

  # Location & Maps
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  url_launcher: ^6.2.1

  # UI
  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.2.0

  # State Management
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true